# Generated by Django 5.2.16 on 2026-08-03 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='core.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
