# Generated by Django 5.2.16 on 2026-08-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_signaturerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='milestone',
            name='source',
            field=models.CharField(default='biahflow', max_length=32),
        ),
        migrations.AddField(
            model_name='task',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(default='biahflow', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('source', 'external_id'), name='core_milestone_unique_external_ref'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('source', 'external_id'), name='core_task_unique_external_ref'),
        ),
    ]
