# Generated by Django 5.2.16 on 2026-08-03 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_client_status_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='party',
            field=models.CharField(choices=[('provider', 'Fornecedor'), ('client', 'Cliente')], default='provider', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='party',
            field=models.CharField(choices=[('provider', 'Fornecedor'), ('client', 'Cliente')], default='provider', max_length=16),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('recording_url', models.URLField(blank=True, default='')),
                ('transcript', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('held', 'Realizada')], default='scheduled', max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.project')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('resolved', 'Resolvida')], default='open', max_length=16)),
                ('party', models.CharField(choices=[('provider', 'Fornecedor'), ('client', 'Cliente')], default='provider', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='core.project')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
