# Generated by Django 5.2.16 on 2026-08-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_milestone_party_task_party_meeting_pendencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
