# Generated by Django 5.2.16 on 2026-08-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aiinteraction_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='drive_folder_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
