# Generated by Django 5.2.16 on 2026-08-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_drive_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerequest',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signaturerequest',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signaturerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('signed', 'Assinado'), ('declined', 'Recusado')], default='pending', max_length=16),
        ),
    ]
