# Generated by Django 5.2.16 on 2026-08-04 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_fit',
            field=models.CharField(blank=True, choices=[('high', 'Alto'), ('medium', 'Médio'), ('low', 'Baixo')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_recommended_action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('attendee_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('held', 'Realizada'), ('canceled', 'Cancelada')], default='scheduled', max_length=16)),
                ('calendar_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('calendar_link', models.URLField(blank=True, default='')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.lead')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
