# Generated by Django 5.2.16 on 2026-08-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aiinteraction_lead_lead_ai_fit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('area', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('building', 'Em construção'), ('active', 'Ativo'), ('paused', 'Pausado')], default='building', max_length=16)),
                ('kpi_label', models.CharField(blank=True, default='', max_length=80)),
                ('kpi_value', models.CharField(blank=True, default='', max_length=80)),
                ('hours_saved_month', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('roi_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_employees', to='core.project')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
