# Generated by Django 5.2.16 on 2026-08-04 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_digitalemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_dimensions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_maturity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_opportunity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_score_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.meeting'),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_score_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_score_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
