# Generated by Django 5.2.16 on 2026-08-05 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_project_ai_dimensions_project_ai_maturity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='core.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='tier',
            field=models.CharField(blank=True, choices=[('discovery_express', 'Discovery Express'), ('discovery_assessment', 'Discovery + Assessment'), ('implantacao', 'Implantação')], default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('tier', ''), _negated=True), ('archived_at__isnull', True)), fields=('tier',), name='one_active_service_per_tier'),
        ),
    ]
