# Generated by Django 5.2.16 on 2026-08-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_seed_service_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerequest',
            name='document_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='signaturerequest',
            name='provider_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
