# Generated by Django 5.2.16 on 2026-08-05 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_signaturerequest_sign_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('discovery', 'Discovery'), ('assessment', 'Assessment'), ('proposal', 'Proposta'), ('contract', 'Contrato')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisão'), ('sent', 'Enviado'), ('accepted', 'Aceito'), ('rejected', 'Recusado')], default='draft', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('ai_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.aiinteraction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.document')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.opportunity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.project')),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.meeting')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
