# Generated by Django 5.2.16 on 2026-08-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_backfill_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Ativo')], default='prospect', max_length=16),
        ),
    ]
