# Generated by Django 5.2.16 on 2026-08-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
