# Generated by Django 5.2.16 on 2026-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_meeting_meeting_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
