# Generated by Django 5.2.16 on 2026-08-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_scheduledjobrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyphase',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
