# Generated by Django 5.2.16 on 2026-08-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_journeyphase_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DigitalEmployeeBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('area', models.CharField(choices=[('comercial', 'Comercial'), ('financeiro', 'Financeiro'), ('rh', 'RH'), ('juridico', 'Jurídico'), ('atendimento', 'Atendimento')], default='comercial', max_length=24)),
                ('description', models.TextField(blank=True, default='')),
                ('kpi_label', models.CharField(blank=True, default='', max_length=80)),
                ('default_hours_saved_month', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('default_roi_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blueprints', to='core.service')),
            ],
            options={
                'ordering': ['area', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='digitalemployee',
            name='blueprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='core.digitalemployeeblueprint'),
        ),
        migrations.AddField(
            model_name='client',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.vertical'),
        ),
        migrations.CreateModel(
            name='BlueprintVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('kpi_label', models.CharField(blank=True, default='', max_length=80)),
                ('default_hours_saved_month', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('default_roi_month', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.digitalemployeeblueprint')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='core.vertical')),
            ],
            options={
                'ordering': ['vertical__position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('blueprint', 'vertical'), name='unique_blueprint_variant')],
            },
        ),
    ]
