# Generated by Django 5.2.16 on 2026-08-07 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_vertical_blueprint_and_client_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalemployee',
            name='kpi_baseline',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='digitalemployee',
            name='kpi_current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='digitalemployee',
            name='kpi_direction',
            field=models.CharField(choices=[('up', 'Maior é melhor'), ('down', 'Menor é melhor')], default='up', max_length=8),
        ),
        migrations.AddField(
            model_name='digitalemployee',
            name='kpi_unit',
            field=models.CharField(blank=True, choices=[('percent', 'Percentual'), ('hours', 'Horas'), ('minutes', 'Minutos'), ('currency', 'Moeda'), ('count', 'Contagem')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='digitalemployeeblueprint',
            name='kpi_direction',
            field=models.CharField(choices=[('up', 'Maior é melhor'), ('down', 'Menor é melhor')], default='up', max_length=8),
        ),
        migrations.AddField(
            model_name='digitalemployeeblueprint',
            name='kpi_unit',
            field=models.CharField(blank=True, choices=[('percent', 'Percentual'), ('hours', 'Horas'), ('minutes', 'Minutos'), ('currency', 'Moeda'), ('count', 'Contagem')], default='', max_length=16),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('health_snapshot', models.JSONField(blank=True, default=dict)),
                ('roi_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisão'), ('published', 'Publicado')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('client_consent', models.BooleanField(default=False)),
                ('consent_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('anonymized', models.BooleanField(default=False)),
                ('consent_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='core.project')),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='core.vertical')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
