# Generated by Django 5.2.16 on 2026-08-07 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_case_and_typed_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_customer_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField()),
                ('method', models.CharField(blank=True, choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('card', 'Cartão'), ('transfer', 'Transferência'), ('other', 'Outro')], default='', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('issued', 'Emitida'), ('paid', 'Paga'), ('overdue', 'Vencida'), ('renegotiated', 'Renegociada'), ('cancelled', 'Cancelada')], default='draft', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('payment_url', models.URLField(blank=True, default='')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.client')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.project')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.service')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'id'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='core_invoic_status_71224b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('number',), name='unique_invoice_number'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='invoice_amount_is_not_negative'), models.CheckConstraint(condition=models.Q(('archived_at__isnull', True)), name='invoice_is_never_archived')],
            },
        ),
    ]
