# Generated by Django 5.2.16 on 2026-08-07 16:39

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_invoice'),
    ]

    operations = [
        # `CREATE EXTENSION IF NOT EXISTS vector`, e **no-op fora do Postgres**: `VectorExtension`
        # herda de `CreateExtension`, cujo `database_forwards` retorna cedo quando
        # `connection.vendor != "postgresql"`. É o que deixa a suíte inteira seguir migrando em
        # SQLite (FDD 029, ADR 0022).
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('review_interval_days', models.PositiveIntegerField(default=180)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('decision', 'Decisão'), ('procedure', 'Procedimento'), ('reference', 'Referência')], default='reference', max_length=16)),
                ('source_path', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('review_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_notified_at', models.DateField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='core.knowledgearea')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['area__position', 'kind', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('heading_path', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=64)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.knowledgepiece')),
            ],
            options={
                'ordering': ['piece_id', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgepiece',
            constraint=models.UniqueConstraint(condition=models.Q(('source_path', ''), _negated=True), fields=('source_path',), name='unique_knowledge_source_path'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('piece', 'position'), name='unique_knowledge_chunk_position'),
        ),
    ]
