# Generated by Django 5.2.16 on 2026-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_seed_knowledge_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
