# Generated by Django 5.2.16 on 2026-08-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_ai_interaction_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrichment',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
