# Generated by Django 5.2.16 on 2026-08-12 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_lead_cnpj_lead_enrichment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('decided_on', models.DateField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes', to='core.project')),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisoes', to='core.meeting')),
            ],
            options={
                'ordering': ['-decided_on', '-created_at'],
            },
        ),
    ]
