# Generated by Django 5.2.16 on 2026-08-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyphase',
            name='requires_gate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='checklist_waiver',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='gate_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='gate_outcome',
            field=models.CharField(blank=True, choices=[('go', 'GO'), ('conditional_go', 'CONDITIONAL GO'), ('redesign', 'REDESIGN'), ('no_go', 'NO-GO')], default='', max_length=16),
        ),
        migrations.CreateModel(
            name='PhaseChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.journeyphase')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('project_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.projectphase')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
