# Generated by Django 5.2.16 on 2026-08-19 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_risco'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cobranca_sinal',
            field=models.CharField(blank=True, choices=[('esqueceu', 'Esqueceu'), ('nao_pode', 'Não pôde pagar'), ('insatisfeito', 'Insatisfeito')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='activity',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='contact',
            name='receives_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CobrancaContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('degrau', models.CharField(choices=[('pre_aviso', 'Pré-aviso'), ('lembrete', 'Lembrete'), ('firme', 'Cobrança firme'), ('escalada', 'Escalada interna'), ('renegociacao', 'Renegociação')], max_length=16)),
                ('canal', models.CharField(choices=[('email', 'E-mail ao cliente'), ('interno', 'Aviso interno')], max_length=8)),
                ('sent_on', models.DateField()),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('to_email', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('ai_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.aiinteraction')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='core.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='core.invoice')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_on', '-id'],
                'indexes': [models.Index(fields=['client', 'sent_on'], name='core_cobran_client__44ea63_idx')],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'degrau'), name='unique_cobranca_degrau_por_fatura'), models.CheckConstraint(condition=models.Q(('archived_at__isnull', True)), name='cobranca_contato_is_never_archived')],
            },
        ),
        migrations.CreateModel(
            name='CobrancaSuspensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('until', models.DateField()),
                ('reason', models.TextField()),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suspensoes', to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suspensoes', to='core.invoice')),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas_suspensas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-until', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('archived_at__isnull', True)), name='cobranca_suspensao_is_never_archived')],
            },
        ),
    ]
