# Generated by Django 5.2.16 on 2026-08-19 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_regua_de_cobranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('promotor', 'Promotor'), ('satisfeito', 'Satisfeito'), ('neutro', 'Neutro'), ('insatisfeito', 'Insatisfeito')], max_length=16)),
                ('fonte', models.CharField(choices=[('declarada', 'Declarada pelo cliente'), ('percebida', 'Percebida por quem entrega')], max_length=16)),
                ('happened_on', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfacoes', to='core.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfacoes', to='core.project')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfacoes', to=settings.AUTH_USER_MODEL)),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfacoes', to='core.meeting')),
            ],
            options={
                'ordering': ['-happened_on', '-created_at'],
            },
        ),
    ]
