# Generated by Django 5.2.16 on 2026-08-19 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_satisfacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfacao',
            name='source_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfacoes', to='core.activity'),
        ),
    ]
