# Generated by Django 5.2.16 on 2026-08-20 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_satisfacao_da_resposta_de_cobranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('volume_mes', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('pessoas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('custo_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retrabalho_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('erros_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('perdas_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('espera_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risco_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='core.client')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to=settings.AUTH_USER_MODEL)),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='core.meeting')),
                ('source_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_mapeados', to='core.project')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('pessoas', models.TextField(blank=True, default='')),
                ('sistema', models.TextField(blank=True, default='')),
                ('dados', models.TextField(blank=True, default='')),
                ('tempo', models.TextField(blank=True, default='')),
                ('erro', models.TextField(blank=True, default='')),
                ('retrabalho', models.TextField(blank=True, default='')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='core.processo')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('forma', models.CharField(choices=[('entrevista', 'Entrevista (o que dizem)'), ('observacao', 'Observação (o que fazem)'), ('artefato', 'Artefato (planilha, PDF, croqui)'), ('sistema', 'Sistema (ERP, CRM, CAD, WhatsApp)'), ('dado', 'Dado (volume, tempo, custo, erro)')], max_length=16)),
                ('rotulo', models.CharField(choices=[('fato', 'Fato'), ('hipotese', 'Hipótese'), ('desconhecido', 'Desconhecido')], max_length=16)),
                ('content', models.TextField()),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to=settings.AUTH_USER_MODEL)),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='core.meeting')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.processo')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='core.processoetapa')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
