# Generated by Django 5.2.17 on 2026-08-24 14:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_discovery_estruturado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('pulse_work_item_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('context', models.TextField(blank=True, default='')),
                ('acceptance_criteria', models.TextField()),
                ('scope_text', models.TextField(blank=True, default='')),
                ('out_of_scope_text', models.TextField(blank=True, default='')),
                ('repository', models.CharField(blank=True, default='', max_length=255)),
                ('milestone_ref', models.CharField(blank=True, default='', max_length=255)),
                ('adr_refs', models.JSONField(blank=True, default=list)),
                ('nfr_refs', models.JSONField(blank=True, default=list)),
                ('fdd_refs', models.JSONField(blank=True, default=list)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('github_issue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('github_issue_url', models.URLField(blank=True, default='')),
                ('github_node_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('provisioned', 'Provisionado'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_handoffs', to='core.project')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineering_handoffs', to='core.task')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('pulse_work_item_id',), name='unique_engineering_handoff_pulse_work_item'), models.UniqueConstraint(condition=models.Q(('github_issue_number__isnull', False), models.Q(('repository', ''), _negated=True)), fields=('repository', 'github_issue_number'), name='unique_engineering_handoff_github_issue')],
            },
        ),
    ]
