# Generated by Django 5.2.17 on 2026-08-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_engineering_handoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=128, unique=True)),
                ('event', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GithubProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_state', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada')], default='open', max_length=16)),
                ('issue_title', models.CharField(blank=True, default='', max_length=255)),
                ('pr_number', models.PositiveIntegerField(blank=True, null=True)),
                ('pr_state', models.CharField(choices=[('none', 'Sem PR'), ('open', 'Aberto'), ('merged', 'Merged'), ('closed', 'Fechado sem merge')], default='none', max_length=16)),
                ('head_sha', models.CharField(blank=True, default='', max_length=40)),
                ('ci_state', models.CharField(choices=[('none', 'Sem check'), ('pending', 'Rodando'), ('success', 'Verde'), ('failure', 'Vermelho')], default='none', max_length=16)),
                ('observed_at', models.DateTimeField()),
                ('observed_via', models.CharField(choices=[('webhook', 'Webhook'), ('reconciliation', 'Reconciliação')], default='webhook', max_length=16)),
                ('last_error_kind', models.CharField(blank=True, choices=[('unavailable', 'GitHub indisponível'), ('forbidden', 'Permissão negada'), ('missing', 'Referência ausente')], default='', max_length=16)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handoff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projection', to='core.engineeringhandoff')),
            ],
            options={
                'ordering': ['-source_updated_at', '-observed_at', '-id'],
            },
        ),
    ]
