# Generated by Django 5.2.17 on 2026-08-27 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Linearizado após a 0047 (linha do tempo, PR #52) para não deixar duas
        # folhas na graph — as duas fatias saíram de branches paralelos sobre a 0045.
        ('core', '0047_delivery_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubDeliveryProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.CharField(max_length=255)),
                ('issue_number', models.PositiveIntegerField()),
                ('issue_url', models.URLField(blank=True, default='')),
                ('projection_status', models.CharField(choices=[('pending', 'Pendente'), ('current', 'Atual'), ('unavailable', 'Indisponível'), ('permission_denied', 'Sem permissão'), ('reference_missing', 'Referência ausente')], default='pending', max_length=24)),
                ('issue_state', models.CharField(choices=[('unknown', 'Desconhecido'), ('open', 'Aberta'), ('closed', 'Fechada')], default='unknown', max_length=16)),
                ('pr_state', models.CharField(choices=[('unknown', 'Desconhecido'), ('none', 'Sem PR'), ('draft', 'Rascunho'), ('open', 'Aberto'), ('closed', 'Fechado'), ('merged', 'Mesclado')], default='unknown', max_length=16)),
                ('pr_number', models.PositiveIntegerField(blank=True, null=True)),
                ('pr_url', models.URLField(blank=True, default='')),
                ('head_sha', models.CharField(blank=True, default='', max_length=64)),
                ('head_ref', models.CharField(blank=True, default='', max_length=255)),
                ('review_state', models.CharField(choices=[('unknown', 'Desconhecido'), ('pending', 'Em revisão'), ('approved', 'Aprovado'), ('changes_requested', 'Mudanças pedidas')], default='unknown', max_length=24)),
                ('ci_state', models.CharField(choices=[('unknown', 'Desconhecido'), ('pending', 'Em execução'), ('success', 'Verde'), ('failure', 'Vermelho')], default='unknown', max_length=16)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivery_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_event_type', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('handoff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projection', to='core.engineeringhandoff')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_projections', to='core.project')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GithubWebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('projection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.githubdeliveryprojection')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='githubdeliveryprojection',
            constraint=models.UniqueConstraint(fields=('repository', 'issue_number'), name='unique_github_delivery_projection_ref'),
        ),
    ]
