# Generated by Django 5.2.17 on 2026-08-27 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_github_projection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('rung', models.CharField(choices=[('discover', 'Discover'), ('prioritize', 'Prioritize'), ('feasibility', '[ Technical Feasibility ]'), ('prove', 'Prove'), ('scale', 'Scale'), ('optimize', 'Optimize')], max_length=16)),
                ('status', models.CharField(choices=[('not_sold', 'Não vendido'), ('active', 'Ativo'), ('done', 'Concluído'), ('skipped', 'Pulada'), ('blocked', 'Bloqueado'), ('awaiting_gate', 'Aguardando decisão de gate'), ('cancelled', 'Replanejado')], default='not_sold', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('waiting_on', models.CharField(blank=True, choices=[('biahflow', 'Biahflow'), ('client', 'Cliente'), ('engineering', 'Engenharia'), ('external', 'Dependência externa'), ('human_gate', 'Human Gate')], default='', max_length=16)),
                ('blocker', models.TextField(blank=True, default='')),
                ('skip_reason', models.TextField(blank=True, default='')),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rungs', to='core.client')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_rungs', to='core.opportunity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_rungs', to='core.project')),
                ('skipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [models.Case(models.When(rung='discover', then=models.Value(0)), models.When(rung='prioritize', then=models.Value(1)), models.When(rung='feasibility', then=models.Value(2)), models.When(rung='prove', then=models.Value(3)), models.When(rung='scale', then=models.Value(4)), models.When(rung='optimize', then=models.Value(5)), output_field=models.PositiveSmallIntegerField()), 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountRungEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('not_sold', 'Não vendido'), ('active', 'Ativo'), ('done', 'Concluído'), ('skipped', 'Pulada'), ('blocked', 'Bloqueado'), ('awaiting_gate', 'Aguardando decisão de gate'), ('cancelled', 'Replanejado')], default='', max_length=16)),
                ('to_status', models.CharField(choices=[('not_sold', 'Não vendido'), ('active', 'Ativo'), ('done', 'Concluído'), ('skipped', 'Pulada'), ('blocked', 'Bloqueado'), ('awaiting_gate', 'Aguardando decisão de gate'), ('cancelled', 'Replanejado')], max_length=16)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.accountrung')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='accountrung',
            constraint=models.UniqueConstraint(fields=('client', 'rung'), name='unique_account_rung'),
        ),
    ]
