# Generated by Django 5.2.17 on 2026-08-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_contact_first_last_name'),
        ('core', '0048_perfil_foto'),
    ]

    operations = [
    ]
