# Generated by Django 5.2.17 on 2026-08-28 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_escada_fde_completa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('running', 'Em andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='planned', max_length=16)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discoveries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='core.project')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DiscoverySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('happened_at', models.DateTimeField()),
                ('participants', models.TextField(blank=True, default='')),
                ('transcript', models.TextField(blank=True, default='')),
                ('discovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.discovery')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_sessions', to='core.meeting')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.artifact')),
            ],
            options={
                'ordering': ['-happened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('interview', 'Entrevista (o que dizem)'), ('observation', 'Observação (o que fazem)'), ('artifact', 'Artefato (planilha, PDF, croqui)'), ('system', 'Sistema (ERP, CRM, CAD, WhatsApp)'), ('data', 'Dado (volume, tempo, custo, erro)')], max_length=16)),
                ('raw_excerpt', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=500)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.client')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_evidence', to=settings.AUTH_USER_MODEL)),
                ('discovery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.discovery')),
                ('legacy_evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_evidence', to='core.evidencia')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.processo')),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structured_evidence', to='core.meeting')),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.discoverysession')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.processoetapa')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('statement', models.TextField()),
                ('epistemic_status', models.CharField(choices=[('fact', 'Fato'), ('hypothesis', 'Hipótese'), ('unknown', 'Desconhecido')], default='hypothesis', max_length=16)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.client')),
                ('evidences', models.ManyToManyField(blank=True, related_name='findings', to='core.evidence')),
                ('legacy_evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_finding', to='core.evidencia')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='core.processo')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_findings', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='core.processoetapa')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('observed_at', models.DateField()),
                ('observation_type', models.CharField(choices=[('initial', 'Primeira observação'), ('revisit', 'Revisita'), ('validation', 'Validação')], default='initial', max_length=16)),
                ('discovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_observations', to='core.discovery')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.processo')),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_observations', to='core.discoverysession')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
            },
        ),
    ]
