"""Os quatro modelos do PRIORITIZE: `PainPoint` → `ImprovementOpportunity` → `PriorityAssessment` → `SolutionHypothesis`.

Fase 4 da ontologia (issue #68, ADR 0049, FDD 048). Só schema: **não há backfill**, e não há por
onde haver — nenhuma das quatro tabelas tem antecessor no banco. A dor existia como prosa em
`Evidencia.content`, e "prosa que talvez seja uma dor" não é dado que se traduza sem alguém ler.

Os quatro nascem com o **nome canônico** e por isso nenhum leva `Meta.db_table`: `db_table`
fixado no nome antigo é o instrumento de quem **renomeia** um modelo já existente (ADR 0052), e
usá-lo aqui inventaria um nome legado que nunca existiu.

`unique_priority_assessment_version` é incondicional de propósito — a avaliação arquivada continua
ocupando o seu número de versão. `unique_chosen_solution_hypothesis` é parcial, no molde de
`unique_active_project_member`: hipóteses concorrentes são o estado normal, duas escolhidas ao
mesmo tempo é contradição, e uma escolha desfeita e arquivada não pode travar a próxima.
"""

# Generated by Django 5.2.17 on 2026-08-29 09:03

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_escada_de_seis_degraus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('impact_type', models.CharField(choices=[('financial', 'Financeiro'), ('operational', 'Operacional'), ('experience', 'Experiência'), ('risk', 'Risco')], max_length=16)),
                ('impact_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('observed', 'Observado'), ('confirmed', 'Confirmado'), ('discarded', 'Descartado')], default='observed', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_points', to='core.account')),
                ('findings', models.ManyToManyField(blank=True, related_name='pain_points', to='core.finding')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pain_points', to='core.process')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pain_points', to='core.processstep')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('desired_change', models.TextField(blank=True, default='')),
                ('impact_hypothesis', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('assessing', 'Em avaliação'), ('prioritized', 'Priorizada'), ('discarded', 'Descartada')], default='open', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_opportunities', to='core.account')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_opportunities', to='core.engagement')),
                ('pain_points', models.ManyToManyField(blank=True, related_name='improvement_opportunities', to='core.painpoint')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PriorityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField()),
                ('impact', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('evidence_strength', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feasibility', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('time_to_value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('economics', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('formula_key', models.CharField(default='v1', max_length=24)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('rationale', models.TextField(blank=True, default='')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_assessments', to=settings.AUTH_USER_MODEL)),
                ('improvement_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.improvementopportunity')),
            ],
            options={
                'ordering': ['-version', '-id'],
                'constraints': [models.UniqueConstraint(fields=('improvement_opportunity', 'version'), name='unique_priority_assessment_version')],
            },
        ),
        migrations.CreateModel(
            name='SolutionHypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('statement', models.TextField()),
                ('intervention', models.TextField(blank=True, default='')),
                ('assumptions', models.TextField(blank=True, default='')),
                ('expected_effect', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('proposed', 'Proposta'), ('chosen', 'Escolhida'), ('discarded', 'Descartada')], default='proposed', max_length=16)),
                ('improvement_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='core.improvementopportunity')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('status', 'chosen')), fields=('improvement_opportunity',), name='unique_chosen_solution_hypothesis')],
            },
        ),
    ]
