"""Os cinco modelos da Fase 5: Feasibility, PROVE, KPI, Measurement e Value Ledger.

Issue #69, ADR 0049/0055, FDD 049. **Só schema, e de propósito**: as colunas
`DigitalEmployee.kpi_baseline` e `kpi_current` continuam de pé aqui, porque é delas que a `0067`
lê o backfill. Remover a origem antes de copiar o dado é a única ordem que não funciona.

Os cinco nascem com o **nome canônico** e por isso nenhum leva `Meta.db_table`: `db_table` fixado
no nome antigo é o instrumento de quem **renomeia** um modelo já existente (ADR 0052), e usá-lo
aqui inventaria um nome legado que nunca existiu.

`unique_live_baseline_measurement` é parcial, no molde de `unique_chosen_solution_hypothesis`: no
máximo **uma** baseline viva por KPI, e uma baseline arquivada por engano não trava a próxima. O
KPI é a janela — a issue pede "por KPI e janela experimental", e como é o KPI que pertence ao
experimento, uma segunda chave seria uma segunda definição de "de quando é este antes".
"""

# Generated by Django 5.2.17 on 2026-08-29 10:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_priorizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeasibilityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('technical_verdict', models.CharField(choices=[('favorable', 'Favorável'), ('caveat', 'Com ressalva'), ('unfavorable', 'Desfavorável')], max_length=16)),
                ('technical_note', models.TextField(blank=True, default='')),
                ('operational_verdict', models.CharField(choices=[('favorable', 'Favorável'), ('caveat', 'Com ressalva'), ('unfavorable', 'Desfavorável')], max_length=16)),
                ('operational_note', models.TextField(blank=True, default='')),
                ('economic_verdict', models.CharField(choices=[('favorable', 'Favorável'), ('caveat', 'Com ressalva'), ('unfavorable', 'Desfavorável')], max_length=16)),
                ('economic_note', models.TextField(blank=True, default='')),
                ('sample', models.TextField(blank=True, default='')),
                ('error_classes', models.TextField(blank=True, default='')),
                ('gate_decision', models.CharField(blank=True, choices=[('go', 'GO'), ('conditional_go', 'CONDITIONAL GO'), ('redesign', 'REDESIGN'), ('no_go', 'NO-GO')], default='', max_length=16)),
                ('evidence', models.ManyToManyField(blank=True, related_name='feasibility_assessments', to='core.evidence')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_assessments', to='core.project')),
                ('solution_hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_assessments', to='core.solutionhypothesis')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('definition', models.TextField(blank=True, default='')),
                ('formula', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, choices=[('percent', 'Percentual'), ('hours', 'Horas'), ('minutes', 'Minutos'), ('currency', 'Moeda'), ('count', 'Contagem')], default='', max_length=16)),
                ('direction', models.CharField(choices=[('up', 'Maior é melhor'), ('down', 'Menor é melhor')], default='up', max_length=8)),
                ('data_source', models.CharField(blank=True, default='', max_length=120)),
                ('cadence', models.CharField(blank=True, default='', max_length=60)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_kpis', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='core.project')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='digitalemployee',
            name='kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_employees', to='core.kpi'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('baseline', 'Baseline'), ('outcome', 'Outcome'), ('monitoring', 'Monitoramento')], max_length=16)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('measured_at', models.DateTimeField()),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.kpi')),
                ('source_evidence', models.ManyToManyField(blank=True, related_name='measurements', to='core.evidence')),
            ],
            options={
                'ordering': ['-measured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProveExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('controlled_scope', models.TextField(blank=True, default='')),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('success_criteria', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('running', 'Em execução'), ('concluded', 'Concluído')], default='planned', max_length=16)),
                ('gate_decision', models.CharField(blank=True, choices=[('scale', 'SCALE'), ('iterate', 'ITERATE'), ('stop', 'STOP')], default='', max_length=16)),
                ('gap_waiver', models.TextField(blank=True, default='')),
                ('gap_waiver_at', models.DateTimeField(blank=True, null=True)),
                ('gap_waiver_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prove_gap_waivers', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prove_experiments', to='core.project')),
                ('solution_hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prove_experiments', to='core.solutionhypothesis')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='kpi',
            name='prove_experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='core.proveexperiment'),
        ),
        migrations.CreateModel(
            name='ValueLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('value_type', models.CharField(choices=[('cost_saving', 'Redução de custo'), ('revenue', 'Receita'), ('risk_reduction', 'Redução de risco'), ('capacity', 'Capacidade')], max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('attribution_method', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('approved', 'Aprovado')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_approvals', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_entries', to='core.engagement')),
                ('outcome_measurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_entries', to='core.measurement')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_entries', to='core.project')),
            ],
            options={
                'verbose_name_plural': 'value ledger entries',
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('kind', 'baseline')), fields=('kpi',), name='unique_live_baseline_measurement'),
        ),
    ]
