# Generated by Django 5.2.17 on 2026-08-31 12:32

import django.db.models.deletion
from django.db import migrations, models


def mark_legacy_engagements_for_review(apps, schema_editor) -> None:
    """Não infere o instrumento de nenhuma linha anterior à invariante 13.

    Uma Account pode ter várias CommercialOpportunities ganhas e vários Documents assinados. O
    banco antigo não registra qual deles **originou** o Engagement; escolher por data, id ou nome
    fabricaria um fato contratual. Todos os vínculos entram nulos e a única afirmação segura é a
    necessidade de remediação humana.

    O reverso é `noop`: `needs_review` já existia para outra ambiguidade do backfill da 0056, então
    voltar não pode apagar um carimbo que talvez já fosse verdadeiro antes desta migração.
    """
    Engagement = apps.get_model("core", "Engagement")
    Engagement.objects.update(needs_review=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_decisao_project_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='originating_commercial_opportunity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originated_engagement', to='core.commercialopportunity'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='originating_design_partner_agreement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originated_design_partner_engagement', to='core.document'),
        ),
        migrations.RunPython(mark_legacy_engagements_for_review, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('needs_review', True), ('originating_commercial_opportunity__isnull', True), ('originating_design_partner_agreement__isnull', True)), models.Q(('originating_commercial_opportunity__isnull', False), ('originating_design_partner_agreement__isnull', True)), models.Q(('originating_commercial_opportunity__isnull', True), ('originating_design_partner_agreement__isnull', False)), _connector='OR'), name='engagement_has_one_origin_or_needs_review'),
        ),
    ]
