# Generated by Django 5.2.17 on 2026-09-01 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """A marca de publicável nos cinco modelos do Discovery (FDD 051, ADR 0060).

    `Process`, `Evidence`, `Finding`, `PainPoint` e `ImprovementOpportunity`. O AS-IS entra com os
    outros quatro porque "o AS-IS validado" da §3 do `language-map` é qualificador sem lastro no
    schema — exatamente como "Evidence marcada como revisada e publicável" era. `ProcessStep` não
    tem marca própria: ele anda com o processo pai.

    **Sem backfill, e a ausência é a decisão.** Nenhuma linha existente nasce publicada: o schema
    não pode decidir retroativamente que uma afirmação sobre a operação de um cliente pode ser
    mostrada a ele. Marcar o que já existe — por `epistemic_status=fact`, por `status=confirmed`,
    por data — fabricaria a revisão humana que a regra 1 da §3 do `language-map` exige, e o
    sintoma seria o pior possível: um cliente lendo, num painel, a suspeita que a casa ainda não
    tinha decidido mostrar. Quem publica é uma pessoa, pela action `publish/`, uma a uma.

    O argumento vale com mais força ainda para o `Process`, e é o motivo de ele ter entrado: o
    AS-IS **é** a descrição da operação do cliente, e `ProcessStep.erro`/`.retrabalho` são a
    caracterização da casa sobre onde o time dele erra. Um backfill aqui mostraria isso a todo
    mundo de uma vez.

    É o mesmo argumento de `mark_legacy_engagements_for_review` na `0074`, com o sinal trocado:
    lá o legado declara a lacuna, aqui o legado **é** a lacuna — e o estado seguro já é o default
    dos dois campos.
    """

    dependencies = [
        ('core', '0074_engagement_originating_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finding',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='improvementopportunity',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='improvementopportunity',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_improvement_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='painpoint',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='painpoint',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_pain_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_processes', to=settings.AUTH_USER_MODEL),
        ),
    ]
