# Generated by Django 5.2.17 on 2026-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_marca_de_publicavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='kind',
            field=models.CharField(blank=True, choices=[('design_partner_agreement', 'Design Partner Agreement')], default='', max_length=32),
        ),
    ]
