# Generated by Django 5.2.17 on 2026-09-02 13:57
#
# `Booking` passa a servir os dois fluxos de agendamento (FDD 013): a pré-venda, que aponta para
# um `Lead`, e o Discovery do Design Partner, que aponta para o `Engagement`. Nenhuma linha
# existente quebra: toda `Booking` de hoje tem `lead` preenchido e `engagement` nulo, que é
# exatamente o primeiro ramo da restrição de "exatamente um" criada no fim.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_document_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.engagement'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.lead'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('engagement__isnull', True), ('lead__isnull', False)), models.Q(('engagement__isnull', False), ('lead__isnull', True)), _connector='OR'), name='booking_has_exactly_one_origin'),
        ),
    ]
