# Generated by Django 5.2.17 on 2026-09-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_booking_do_discovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(blank=True, choices=[('design_partner_agreement', 'Design Partner Agreement'), ('nda', 'NDA'), ('commercial_contract', 'Contrato comercial'), ('proposal', 'Proposta')], default='', max_length=32),
        ),
    ]
