# Generated by Django 5.2.17 on 2026-09-03 12:53
#
# O grupo do cliente no WhatsApp, aberto pelo kickoff (issue #110, emenda de 03/09/2026 na
# FDD 008). Dois campos porque são dois fatos: o JID identifica o grupo para mandar mensagem
# depois, e o link de convite é o que se entrega a uma pessoa — a UAZAPI pode devolver o primeiro
# sem o segundo.
#
# Aditiva e sem backfill: projeto que já existe fica com os dois vazios e **não** ganha grupo
# retroativo. Abrir grupo para entrega em curso é ato de operação, não de deploy.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_document_kind_classifica_e_nao_so_abre_mandato'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='whatsapp_group_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='whatsapp_group_invite_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
