# Generated by Django 5.2.17 on 2026-09-03 19:08
#
# O papel do signatário (issue #115, ADR 0065). Ele decide onde a assinatura aparece na página,
# qual `action` vai para o fornecedor, e para quem sai o convite do Discovery quando a rodada fecha.
#
# Aditiva e **sem backfill de propósito**: `counterparty` é o default porque, até esta issue, o
# único signatário que uma solicitação tinha era a outra parte — toda linha já gravada está certa
# sob esse default. Um default vazio obrigaria a adivinhar o papel de cada assinatura histórica.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_o_grupo_de_whatsapp_do_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerequest',
            name='signer_role',
            field=models.CharField(choices=[('house', 'Biahflow'), ('counterparty', 'Parte contratante'), ('witness', 'Testemunha')], default='counterparty', max_length=16),
        ),
    ]
