# Generated by Django 5.2.17 on 2026-09-04 01:28
#
# O carimbo de "é PDF?" do documento (issue #120, DAP `dap-assinatura-com-papeis-r1`, E1). É o que
# permite à tela avisar, antes do envio, que as assinaturas não vão cair sobre as linhas — sem
# baixar o arquivo do Drive a cada linha da listagem.
#
# Aditiva e **sem backfill de propósito**: `null` é "não medido", nunca `False`. O legado que mora
# no Drive continua sem carimbo, e a lacuna dele fica desconhecida em vez de inventada — dizer
# `False` ali afirmaria sobre bytes que ninguém leu.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_a_rodada_legada_ganha_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_is_pdf',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
