# Generated by Django 5.2.17 on 2026-09-04 06:49
#
# O grupo do cliente no WhatsApp passa a nascer no `Engagement` (issue #119, 04/09/2026): o mandato
# é, por definição (ADR 0050), "o mesmo trabalho", e um canal por projeto abria três grupos com o
# mesmo cliente num mandato com Discovery → Feasibility → PROVE. Mesmo par de sempre — JID e link
# de convite são dois fatos, não um em dois formatos.
#
# Aditiva e sem backfill, e a ausência de backfill é o ponto da decisão, não descuido: os grupos já
# criados apontam para `Project.whatsapp_group_id`/`.whatsapp_group_invite_url`, que ficam como
# estão — renomear ou migrar um grupo que já existe, com gente dentro, é efeito externo visível ao
# cliente.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_o_carimbo_de_pdf_do_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='whatsapp_group_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='engagement',
            name='whatsapp_group_invite_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
