# Generated by Django 5.2.17 on 2026-09-05 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_o_contato_de_cobranca_fala_ingles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_return_year', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payback_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_state_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_state_cost_source', models.JSONField(blank=True, default=dict)),
                ('rationale', models.TextField()),
                ('assumptions', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='draft', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_cases_decided', to=settings.AUTH_USER_MODEL)),
                ('improvement_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_cases', to='core.improvementopportunity')),
                ('priority_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_cases', to='core.priorityassessment')),
                ('solution_hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_cases', to='core.solutionhypothesis')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('status', 'approved')), fields=('improvement_opportunity',), name='unique_approved_business_case')],
            },
        ),
    ]
