# Generated by Django 5.2.17 on 2026-09-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_a_justificativa_do_investimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverysession',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
