export type PipelineStage = { id: number; name: string; kind: "open" | "won" | "lost"; position: number; opportunity_count?: number; estimated_total?: string | null };
export type Opportunity = { id: number; client: number; contact: number | null; title: string; scope: string; estimated_value: string; stage: number; stage_name: string; owner: number; expected_close_date: string; service: number | null; service_name: string; service_tier: ServiceTier; project: number | null };
export type AiScoreDimension = { label: string; score: number };
export type Project = { id: number; name: string; description: string; client: number; owner: number; start_date: string; due_date: string; status: string; service: number | null; actual_value: string; cost: string; is_overdue: boolean; ai_maturity: number | null; ai_opportunity: number | null; ai_dimensions: AiScoreDimension[]; ai_score_summary: string; ai_scored_at: string | null; ai_score_reviewed: boolean };
export type ServiceTier = "discovery_express" | "discovery_assessment" | "implantacao" | "";
export type Service = { id: number; name: string; active: boolean; tier: ServiceTier; tier_display: string; list_price: string; summary: string };
export type TierFunnelRow = { tier: ServiceTier; label: string; total: number; open: number; won: number; lost: number; estimated_total: number; win_rate: number | null };
export type StageFunnelRow = { kind: ArtifactKind; label: string; total: number; sent: number; accepted: number; rejected: number; acceptance_rate: number | null; reached: number };
export type RoiRow = { label: string; revenue: number; cost: number; roi: number | null };
export type Analytics = {
  funnel: {
    leads: { total: number; by_status: Record<string, number> };
    opportunities: { open: number; won: number; lost: number };
    projects: { total: number; by_status: Record<string, number> };
    by_tier: TierFunnelRow[];
    by_stage: StageFunnelRow[];
  };
  win_rate: number | null;
  avg_ticket: number;
  avg_cycle_days: number | null;
  pipeline: { id: number; name: string; kind: string; position: number; opportunity_count: number; estimated_total: number | null }[];
  roi: { revenue: number; cost: number; roi: number | null; by_client: RoiRow[]; by_service: RoiRow[] };
};
export type ClientStatus = "prospect" | "active";
export type Client = { id: number; name: string; legal_name: string; tax_id: string; owner: number; status: ClientStatus };
export type Contact = { id: number; client: number; name: string; email: string; phone: string; job_title: string };
export type WorkItemStatus = "todo" | "in_progress" | "done";
export type Party = "provider" | "client";
export type Milestone = { id: number; project: number; title: string; description: string; owner: number; due_date: string; completed_at: string | null; status: WorkItemStatus; party: Party; is_overdue: boolean };
export type Task = Milestone & { milestone: number | null };
export type Meeting = { id: number; project: number; title: string; date: string; meeting_url: string; recording_url: string; transcript: string; status: "scheduled" | "held" };
export type Pendencia = { id: number; project: number; title: string; description: string; status: "open" | "resolved"; party: Party; owner: number | null; resolved_at: string | null };
export type SignatureRequest = { id: number; signer_email: string; status: "pending" | "signed" | "declined"; sign_url: string; reminded_at: string | null; signed_at: string | null; created_at: string };
export type DocumentEntry = { id: number; client: number | null; opportunity: number | null; project: number | null; file: string; drive_link: string; original_name: string; uploaded_by: number; created_at: string; signature_requests: SignatureRequest[] };
export type ArtifactKind = "discovery" | "assessment" | "proposal" | "contract";
export type ArtifactStatus = "draft" | "review" | "sent" | "accepted" | "rejected";
export type Artifact = { id: number; kind: ArtifactKind; kind_display: string; status: ArtifactStatus; status_display: string; title: string; content: string; opportunity: number | null; project: number | null; source_meeting: number | null; document: number | null; ai_interaction: number | null; created_by: number; sent_at: string | null; decided_at: string | null; created_at: string; updated_at: string };
export type Dashboard = { pipeline: PipelineStage[]; active_projects: number; overdue_count: number; upcoming_tasks: { id: number; title: string; due_date: string; project_id: number }[] };
export type SessionUser = { id: number; username: string; first_name: string; last_name: string; email: string; role: "admin" | "sales" | "delivery" };
export type Role = "admin" | "sales" | "delivery";
export type Invitation = { id: number; email: string; role: Role; expires_at: string; accepted_at: string | null; created_at: string };
export type IntegrationFlag = { key: string; label: string; enabled: boolean; configured: boolean; toggleable: boolean };
export type AppConfig = { ai_enabled: boolean; calendar_enabled: boolean; esign_enabled: boolean; integrations: IntegrationFlag[] };
export type RiskSignal = { label: string; detail: string; weight: number };
export type RiskForecast = { predicted_finish_date: string; delay_days: number; basis: string };
export type RiskAssessment = { project_id: number; name: string; score: number; level: string; signals: RiskSignal[]; forecast: RiskForecast | null };
export type HealthLevel = "saudável" | "atenção" | "crítico";
export type HealthAssessment = { project_id: number; name: string; score: number; level: HealthLevel; signals: RiskSignal[] };
export type ClientOverview = {
  client_id: number;
  name: string;
  status: ClientStatus;
  roi: { revenue: number; cost: number; roi: number | null };
  health: { score: number; level: HealthLevel; project_id: number } | null;
  risk_level: string | null;
  phase: { name: string; status: JourneyPhaseStatus } | null;
  next_meeting: { title: string; date: string } | null;
  ai_score: AiScore | null;
};
export type AiScore = { maturity: number | null; opportunity: number | null; dimensions: AiScoreDimension[]; summary: string; scored_at: string };
export type AgentReply = { text: string; interaction: number };
export type Recommendation = { kind: string; label: string; detail: string; url: string };
export type Notification = { id: number; kind: string; message: string; url: string; read: boolean; created_at: string };
/** Participação numa equipe de projeto — é o que dá acesso a quem é da Entrega (RFC 0003). */
export type ProjectMember = { id: number; project: number; user: number; user_name: string; user_username: string; user_role: Role; added_by: number | null; created_at: string };

export type DigitalEmployeeStatus = "building" | "active" | "paused";
export type DigitalEmployee = { id: number; project: number; name: string; area: string; description: string; status: DigitalEmployeeStatus; kpi_label: string; kpi_value: string; hours_saved_month: string; roi_month: string };
export type JourneyPhaseStatus = "locked" | "active" | "done";
export type ProjectDeliverableStatus = "pending" | "delivered";
export type ProjectDeliverable = { id: number; project_phase: number; name: string; status: ProjectDeliverableStatus; document: number | null; position: number; delivered_at: string | null };
export type ProjectPhase = { id: number; project: number; phase: number; phase_name: string; phase_description: string; phase_position: number; status: JourneyPhaseStatus; started_at: string | null; completed_at: string | null; target_date: string | null; deliverables: ProjectDeliverable[] };
export type PhaseDeliverableTemplate = { id: number; phase: number; name: string; position: number };
export type JourneyPhaseTemplate = { id: number; name: string; description: string; position: number; deliverables: PhaseDeliverableTemplate[] };
export type LeadStatus = "new" | "contacted" | "qualified" | "discarded";
export type LeadFit = "high" | "medium" | "low" | "";
export type Lead = { id: number; name: string; email: string; company: string; phone: string; message: string; source: string; status: LeadStatus; ai_fit: LeadFit; ai_score: number | null; ai_summary: string; ai_recommended_action: string; qualified_at: string | null; client: number | null; opportunity: number | null; created_at: string };
